#!/usr/bin/python

import os
import argparse
import manage_capabilities

if __name__ == "__main__":
    path, _ = os.path.split(os.path.realpath(__file__))
    os.chdir(path)

    parser = argparse.ArgumentParser(description="Utility to manage the capabilities exposed by the bundle box.")

    parser.add_argument("-m", "--mac", metavar="mac_addr", type=str, required=True,
        help="The MAC address of the device for which you want to add a capability.")

    parser.add_argument("-n", "--name", metavar="capability_name", type=str, required=True,
        help="The name of the capability as it will show up in the capability directory")

    parser.add_argument("-d", "--description", metavar="capability_desc", type=str, required=True,
        help="The description of the capability as it will show up in the capability directory")

    args = parser.parse_args()

    manage_capabilities.add_capability(args.mac, args.name, args.description)
    manage_capabilities.pretty_print_directory() # todo: remove
