version: '2'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn-server
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    volumes:
      - ./openvpn-data/conf:/etc/openvpn

  mqtt:
    image: micwy/vernemq:1.11.0-alpine
    container_name: VerneMQ
    ports:
      - "1883:1883/tcp"
      - "8080:8080/tcp"
    networks:
      intersect_server:
        ipv4_address: 172.16.0.2
    restart: unless-stopped
    environment:
      DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS: 5
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"

  subscriber:
    build: .
    ports:
      - "1024:1024/tcp"
    networks:
      intersect_server:
        ipv4_address: 172.16.0.3
    restart: unless-stopped

networks:
  intersect_server:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/12
          gateway: 172.16.0.1
