version: '2'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn-server
    ports:
      - "1194:1194/udp"
    networks:
      intersect_docker_network:
        ipv4_address: 192.168.201.4
        ipv4_address: 192.168.201.5
    restart: unless-stopped
    volumes:
      - ./openvpn-data/conf:/etc/openvpn

  directory:
    build: .
    ports:
      - "80:8080/tcp"
    networks:
      intersect_docker_network:
        ipv4_address: 192.168.201.3
    restart: unless-stopped

networks:
  intersect_docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24
          gateway: 192.168.201.4
