version: '2'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn-server
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    volumes:
      - ./openvpn-data/conf:/etc/openvpn

  mqtt:
    image: micwy/vernemq:1.11.0-alpine
    container_name: VerneMQ
    ports:
      - "1883:1883/tcp"
      - "8080:8080/tcp"
    restart: unless-stopped
    environment:
      DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS: 5
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"

  subscriber:
    build: .
